//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admlogin.LoginServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginServiceReference1.IloginService")]
    public interface IloginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginService/DoWork", ReplyAction="http://tempuri.org/IloginService/DoWorkResponse")]
        string DoWork(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginService/DoWork", ReplyAction="http://tempuri.org/IloginService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginService/Logout", ReplyAction="http://tempuri.org/IloginService/LogoutResponse")]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IloginService/Logout", ReplyAction="http://tempuri.org/IloginService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IloginServiceChannel : Admlogin.LoginServiceReference1.IloginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IloginServiceClient : System.ServiceModel.ClientBase<Admlogin.LoginServiceReference1.IloginService>, Admlogin.LoginServiceReference1.IloginService {
        
        public IloginServiceClient() {
        }
        
        public IloginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IloginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IloginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IloginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork(string username, string password) {
            return base.Channel.DoWork(username, password);
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync(string username, string password) {
            return base.Channel.DoWorkAsync(username, password);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
    }
}
